name: Code Coverage (CI)

on:
  push:
    branches:
      - 'martian-robots'

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v1
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        test-script: yarn test:unit