name: Jest Runner (CI)

on:
  push:
    branches:
      - 'martian-robots'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run tests
        run: yarn test:unit
  coverage:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v1
      - name: Install modules
        run: yarn install
      - uses: ArtiomTr/jest-coverage-report-action@v2