name: Jest Runner (CI)

on:
  push:
    branches:
      - 'martian-robots'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: yarn test:unit

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
      - name: Coverage report